### ISSUE TITLE
Don't have ~/.config/dwmbar/dwmbarrc

### ISSUE THREAD

**Issue by hamensman** [thytom/dwmbar#22]
How do you get `~/.config/dwmbar/dwmbarrc`?  I can't find it at all.

**Comment by Um1aut** [comment]
idk too

**Comment by EnigmaticJihad** [comment]
There's nothing in `~/.config/dwmbar` by default. The _bar script, config & modules_ are in the `/usr/share/dwmbar` directory. You need to copy them to `~/.config/dwmbar`
