### ISSUE TITLE
[Error] - does not start due to syntax error

### ISSUE THREAD

**Issue by ThisIsLamer** [thytom/dwmbar#30]
I am unable to start dwmbar due to an incomprehensible syntax error.

I installed it on arch using the yay package manager. Package: dwmbar-git

I wrote the following to the configuration file `MODULES = "cpuload ram wifi time"`

![image](https://user-images.githubusercontent.com/67061567/145679768-ef1ffd21-682c-48e2-b4d2-cd8b56aa5251.png)

**Comment by thytom** [comment]
Two things that could be causing this:

`MODULES = "cpuload ram wifi time"` should be written without spaces around the `=`: `MODULES="cpuload ram wifi time"`.

It also looks like it's not interpreting your config file.

Is the config file definitely located at `/home/lamer/.config/dwmbar/config`?

Another issue I can see is that you don't have `xsetroot` installed. Are you using DWM or some other window manager?

**Comment by ThisIsLamer** [comment]
Yes, i use DWM. I thought that the MODULES variable should be written in the `dwmbarrc` file. After fixing, I got a new error

![image](https://user-images.githubusercontent.com/67061567/145682216-a87015dc-9fbf-4096-8aec-b21f6d829378.png)


![image](https://user-images.githubusercontent.com/67061567/145682234-e26057a2-b201-4ede-ad35-c5c0d755125c.png)

**Comment by ThisIsLamer** [comment]
After installation xsetroot

![image](https://user-images.githubusercontent.com/67061567/145682308-ad09daaf-4fba-4b31-b786-b01b0adaeb4d.png)
