### ISSUE TITLE
Hide Updates if none

### ISSUE THREAD

**Issue by Lygaen** [thytom/dwmbar#33]
Hi !
I realized while using the "archupdates" modules that it is still showing even thought there is not update to do, using a lot of space for nothing.
Is it possible to disable/hide it when no updates are available ? It could even be a feature !
Thanks,

Lygaen

**Comment by thytom** [comment]
Hello,

Sorry, I've not been so active on maintaining this since I stopped using it but I glanced at this and it seemed easy. If you still want this, you can download the 33-arch-updates branch and test it out. If it works like you want, I'll merge it into the master.
