### ISSUE TITLE
Problem with install.sh script

### ISSUE THREAD

**Issue by anurag3301** [thytom/dwmbar#34]
Hey, I think there is a bug with the install script. This line to be precise.
https://github.com/thytom/dwmbar/blob/574f5703c558a56bc9c354471543511255423dc7/install.sh#L36

If you have already run the install script, you make some changes to any module and wish to run the install script again. This is going to copy the entire module directory and place it in `/usr/share/dwmbar/modules` resulting in the creation of `/usr/share/dwmbar/modules/modules` where your updated modules are placed but are not used.

![image](https://user-images.githubusercontent.com/52702259/193408391-03b26214-c49b-4bb4-9e60-169179a42e95.png)

I fixed it by doing following
```sh
cp -r ./modules/* "/usr/share/dwmbar/modules"
```

Have a look at this and let me know if I did anything wrong or how it can be done in a better way. :)

**Comment by thytom** [comment]
Woah, I didn't realize people still used this :o

Your solution works if you've already installed `dwmbar` once before, but I just tested the change on a fresh installation and it fails to write the initial directory.

Changing the line to

```
 cp -rT "./modules" "/usr/share/dwmbar/modules" 
```

Seems to fix the bug, so I'll push that change now.

You can also copy your modified modules to `.config/dwmbar/modules/.` and it should automatically override those in `/usr/share` next time you start `dwmbar`, if you're looking for an easier way to modify things.

If you come up with any cool modules or fixes/features, feel free to make a pull request, I'd be happy to merge any changes!
